### ISSUE TITLE
Can I install this on a cpanel + litespeed web server?

### ISSUE THREAD

**Issue by lostsoul6** [L1teD/cs2-WeaponPaints-website#26]
Hello @L1teD ,

I had a brief look at this website and it seems it works on nginx only . Can this be installed on a cpanel with node.js and litespeed webserver ?

What is the difference between public and private version?

I want to install the website on a server other than my game server . Is that possible?

Thank you .

**Comment by L1teD** [comment]
Hi, i don't exactly know about cpanel with node.js, since i don't use cpanel, but i heard that people got the web working on cpanel

Private version offers premium system, multiple servers support, LTS, workshop (collections) system, many languages and styles
Also i will add features that users will want to

You can install website on any server you want, only thing is required is to have same database (website and cs2 server)

**Comment by lostsoul6** [comment]
@L1teD I wasn't able to run it on cpanel . I sent you a message on discord with my payment receipt and my server information . Please kindly install the website for me on the vps server I provided . Thank you .
